export const ADD_CONNECTION = 'ADD_CONNECTION';
export const OPEN_CONNECTION = 'OPEN_CONNECTION';
export const CLOSE_CONNECTION = 'CLOSE_CONNECTION';
export const REMOVE_CONNECTION = 'REMOVE_CONNECTION';
